import { Component, computed, inject } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { toSignal } from '@angular/core/rxjs-interop';
import { startWith } from 'rxjs';

import { ConversionStore } from '../../store/conversion.store';
import { Currencies } from '../../services/currencies';
import { Picker } from '../../components/picker/picker';
import { InputComponent } from '../../components/input/input';

import { NgIcon, provideIcons } from '@ng-icons/core';
import { cssArrowsExchange } from '@ng-icons/css.gg';

export interface CurrencyOption {
  value: string;
  label: string;
  imageUrl: string;
}

/**
 * Container component to handle currency selection pickers and maps values into the
 * state store. Uses reactive signals to optimize change detection performance for
 * static derivations.
 */
@Component({
  selector: 'app-conversion-form',
  imports: [ReactiveFormsModule, NgIcon, Picker, InputComponent],
  providers: [provideIcons({ cssArrowsExchange })],
  templateUrl: './conversion-form.html',
  styleUrl: './conversion-form.scss',
})
export class ConversionForm {
  private currencyService = inject(Currencies);
  protected store = inject(ConversionStore);

  // Note: The following snippet was generated by an AI assistant
  //
  // Bridges FormControl value updates into a Signal stream, seeding it with the
  // initial value to prevent undefined states.
  private readonly sourceCurrencyValue = toSignal(
    this.store.sourceCurrency.valueChanges.pipe(startWith(this.store.sourceCurrency.value)),
    { requireSync: true },
  );

  // Memoizes the currency symbol lookup, executing only when the underlying source
  // currency changes.
  public readonly currencySymbol = computed(() =>
    this.currencyService.getSymbol(this.sourceCurrencyValue()),
  );

  public readonly currencyOptions: CurrencyOption[] = this.currencyService
    .getCurrencies()
    .map((c) => ({
      value: c.code,
      label: c.name,
      imageUrl: c.flagUrl,
    }));

  exchange() {
    const source = this.store.sourceCurrency.value;
    const target = this.store.targetCurrency.value;
    this.store.sourceCurrency.setValue(target);
    this.store.targetCurrency.setValue(source);
  }
}
